# Generated by Django 5.0.1 on 2024-02-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('reorder_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('reorder_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.AlterField(
            model_name='hardware',
            name='reorder_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='kit',
            name='reorder_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
