# Generated by Django 5.0.1 on 2024-02-29 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0002_hardwarekit_part_alter_hardware_reorder_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.hardware')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.kit')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='hardware',
            field=models.ManyToManyField(through='partsdatabase.KitHardware', to='partsdatabase.hardware'),
        ),
        migrations.CreateModel(
            name='PartKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('reorder_quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.kit')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.part')),
            ],
        ),
    ]
