# Generated by Django 5.0.1 on 2024-02-29 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0003_kithardware_kit_hardware_partkit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KitHardware',
            new_name='KitHardwareAssembly',
        ),
        migrations.RenameModel(
            old_name='PartKit',
            new_name='KitPartAssembly',
        ),
        migrations.AddField(
            model_name='kit',
            name='part',
            field=models.ManyToManyField(through='partsdatabase.KitPartAssembly', to='partsdatabase.part'),
        ),
        migrations.CreateModel(
            name='HardwareKitAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.hardware')),
                ('hardware_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.hardwarekit')),
            ],
        ),
        migrations.AddField(
            model_name='hardwarekit',
            name='hardware',
            field=models.ManyToManyField(through='partsdatabase.HardwareKitAssembly', to='partsdatabase.hardware'),
        ),
        migrations.CreateModel(
            name='KitHardwareKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hardware_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.hardwarekit')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.kit')),
            ],
        ),
        migrations.AddField(
            model_name='kit',
            name='hardware_kit',
            field=models.ManyToManyField(through='partsdatabase.KitHardwareKit', to='partsdatabase.hardwarekit'),
        ),
    ]
