# Generated by Django 5.0.1 on 2024-02-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0004_rename_kithardware_kithardwareassembly_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kithardwareassembly',
            unique_together={('kit', 'hardware')},
        ),
    ]
