# Generated by Django 5.0.1 on 2024-03-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0005_alter_kithardwareassembly_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kithardwareassembly',
            options={'ordering': ['kit', 'hardware']},
        ),
        migrations.AlterField(
            model_name='kit',
            name='hardware',
            field=models.ManyToManyField(blank=True, through='partsdatabase.KitHardwareAssembly', to='partsdatabase.hardware'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='hardware_kit',
            field=models.ManyToManyField(blank=True, through='partsdatabase.KitHardwareKit', to='partsdatabase.hardwarekit'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='part',
            field=models.ManyToManyField(blank=True, through='partsdatabase.KitPartAssembly', to='partsdatabase.part'),
        ),
    ]
