# Generated by Django 5.0.1 on 2024-03-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0006_alter_kithardwareassembly_options_alter_kit_hardware_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarekit',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kit',
            name='hardware',
            field=models.ManyToManyField(null=True, through='partsdatabase.KitHardwareAssembly', to='partsdatabase.hardware'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='hardware_kit',
            field=models.ManyToManyField(null=True, through='partsdatabase.KitHardwareKit', to='partsdatabase.hardwarekit'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='part',
            field=models.ManyToManyField(null=True, through='partsdatabase.KitPartAssembly', to='partsdatabase.part'),
        ),
    ]
