# Generated by Django 5.0.1 on 2024-03-01 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0007_alter_hardwarekit_quantity_alter_kit_hardware_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='hardware_kit',
        ),
        migrations.RemoveField(
            model_name='kit',
            name='part',
        ),
    ]
