# Generated by Django 5.0.1 on 2024-03-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0008_remove_kit_hardware_kit_remove_kit_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='hardware',
            field=models.ManyToManyField(blank=True, null=True, through='partsdatabase.KitHardwareAssembly', to='partsdatabase.hardware'),
        ),
    ]
