# Generated by Django 5.0.1 on 2024-03-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0009_alter_kit_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='hardware',
            field=models.ManyToManyField(blank=True, through='partsdatabase.KitHardwareAssembly', to='partsdatabase.hardware'),
        ),
    ]
