# Generated by Django 5.0.1 on 2024-03-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0010_alter_kit_hardware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='location',
            field=models.CharField(default='A01', max_length=10),
        ),
    ]
