# Generated by Django 5.0.1 on 2024-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0012_alter_hardware_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(blank=True, default='A01', max_length=10),
        ),
    ]
