# Generated by Django 5.0.1 on 2024-03-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0013_alter_part_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hardwarekitassembly',
            unique_together={('hardware_kit', 'hardware')},
        ),
    ]
