# Generated by Django 5.0.1 on 2024-03-04 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0014_alter_hardwarekitassembly_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartHKAssembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('hardware_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.hardwarekit')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsdatabase.part')),
            ],
            options={
                'unique_together': {('hardware_kit', 'part')},
            },
        ),
        migrations.AddField(
            model_name='hardwarekit',
            name='part',
            field=models.ManyToManyField(through='partsdatabase.PartHKAssembly', to='partsdatabase.part'),
        ),
    ]
