# Generated by Django 5.0.1 on 2024-03-04 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0015_parthkassembly_hardwarekit_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarekitassembly',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='parthkassembly',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
