# Generated by Django 5.0.1 on 2024-03-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0016_alter_hardwarekitassembly_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarekitassembly',
            options={'ordering': ['hardware']},
        ),
    ]
