# Generated by Django 5.0.1 on 2024-03-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0017_alter_hardwarekitassembly_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parthkassembly',
            options={'ordering': ['part']},
        ),
    ]
