# Generated by Django 5.0.1 on 2024-03-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0018_alter_parthkassembly_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kithardwarekit',
            options={'ordering': ['kit', 'hardware_kit']},
        ),
        migrations.AlterUniqueTogether(
            name='kithardwarekit',
            unique_together={('kit', 'hardware_kit')},
        ),
    ]
