# Generated by Django 5.0.1 on 2024-03-09 00:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0019_alter_kithardwarekit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kithardwarekit',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
