# Generated by Django 5.0.1 on 2024-03-09 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0021_alter_kithardwareassembly_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kitpartassembly',
            options={'ordering': ['kit', 'part']},
        ),
        migrations.AlterUniqueTogether(
            name='kitpartassembly',
            unique_together={('kit', 'part')},
        ),
        migrations.AlterField(
            model_name='kitpartassembly',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.RemoveField(
            model_name='kitpartassembly',
            name='reorder_quantity',
        ),
        migrations.RemoveField(
            model_name='kitpartassembly',
            name='unit_price',
        ),
    ]
