# Generated by Django 5.0.1 on 2024-03-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsdatabase', '0022_alter_kitpartassembly_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='hardware_kit',
            field=models.ManyToManyField(blank=True, through='partsdatabase.KitHardwareKit', to='partsdatabase.hardwarekit'),
        ),
        migrations.AddField(
            model_name='kit',
            name='part',
            field=models.ManyToManyField(blank=True, through='partsdatabase.KitPartAssembly', to='partsdatabase.part'),
        ),
    ]
