# Generated by Django 5.0.1 on 2024-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('partslog', '0003_alter_log_approved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='log',
            name='approved_by',
            field=models.ManyToManyField(limit_choices_to={'name': 'managers'}, related_name='approved_logs', to='auth.group'),
        ),
    ]
