# Generated by Django 5.0.1 on 2024-04-16 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partslog', '0004_remove_log_approved_by_log_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='log',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='approved_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
