# Generated by Django 5.0.1 on 2024-04-17 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partslog', '0005_remove_log_approved_by_log_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
