# Generated by Django 5.0.1 on 2024-04-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partslog', '0006_log_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='created_by',
        ),
    ]
